#              sunny:1,                                 overcast:3,                       rain,2,                        
#         high:0    ,normal:1                                                        strong:0,    weak:1, 
#           no:0      yes:1                             yes:1                             no:0      yes:1

In [1]:
import pandas as pd

In [13]:
data=pd.read_csv('decision_tree.csv')

In [14]:
data

     outlook Humidity    wind playtennis
0      sunny     high  strong         no
1       rain   normal    weak        yes
2      sunny     high    weak         no
3   overcast   normal  strong        yes
4       rain     high    weak        yes
5      sunny     high  strong         no
6       rain   normal    weak        yes
7       rain   normal  strong         no
8   overcast     high    weak        yes
9   overcast     high  strong        yes
10      rain   normal  strong         no
11     sunny   normal    weak        yes
12  overcast   normal  strong        yes
13     sunny   normal    weak        yes
14      rain     high    weak        yes

In [15]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()

In [16]:
dict1={'sunny':1,'rain':2,'overcast':3}
data['outlook']=data['outlook'].map(dict1)
data['Humidity']=pd.get_dummies(data['Humidity'],drop_first=True)
data['wind']=pd.get_dummies(data['wind'],drop_first=True)
data['playtennis']=pd.get_dummies(data['playtennis'],drop_first=True)

In [17]:
data

    outlook  Humidity  wind  playtennis
0         1         0     0           0
1         2         1     1           1
2         1         0     1           0
3         3         1     0           1
4         2         0     1           1
5         1         0     0           0
6         2         1     1           1
7         2         1     0           0
8         3         0     1           1
9         3         0     0           1
10        2         1     0           0
11        1         1     1           1
12        3         1     0           1
13        1         1     1           1
14        2         0     1           1

In [19]:
model.fit(data[['outlook','Humidity','wind']],data['playtennis'])

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [ ]:
#              sunny:1,                                 overcast:3,                       rain,2,                        
#         high:0    ,normal:1                                                        strong:0,    weak:1, 
#           no:0      yes:1                             yes:1                             no:0      yes:1

In [27]:
y_pred=model.predict([[3,1,0]])
y_pred

array([1], dtype=uint8)